"""Deterministic BOM parser tests (docs/bom-checker-build.md §8/§9).

Three layers:

  - Synthetic fixtures (tests/fixtures/bom, generated by make_fixtures.py):
    every recognised layout with fake names, detected as the intended format
    and parsed to *exactly* the reviewed normalized/<file>.json — quantities,
    categories, config names, server models, node counts and rawText.
  - Unit: the strict template (round trip incl. nodeCount, error listing),
    categorize()/should_drop() on the survey's §4 corner cases and the
    negated indicators, the Dell 30-character de-wrap, quantity coercion.
  - Archive-optional parity: the real SC//Design fixtures in _archive/ (git-
    ignored; skipped when absent) must detect as the documented format, carry
    the documented config names / server models / node counts, and match
    SC//Design's normalized JSON on the load-bearing categories as multisets
    of (part number, quantity) — except for the deviations pinned per file
    in ACCEPTED_DEVIATIONS, each with the reason it is right (or harmless).
    Anything else fails with the offending tuples in the message.

Run: .venv/bin/python -m pytest tests/test_bom_parsers.py -q
"""
import io
import json
import os
import re
import sys
from collections import Counter

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "app"))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "fixtures", "bom"))

import pytest  # noqa: E402
from openpyxl import Workbook, load_workbook  # noqa: E402

from bom.normalize import NormalizedBOM  # noqa: E402
from bom.parsers import (  # noqa: E402
    FORMAT_LABELS,
    UnrecognizedFormat,
    detect_format,
    detect_vendor,
    parse_file,
)
from bom.parsers import template  # noqa: E402
from bom.parsers.common import (  # noqa: E402
    categorize,
    dewrap_dell,
    is_absence,
    is_m2_media,
    s,
    server_model_from_text,
    should_drop,
    split_nx,
    to_int,
)
from bom.parsers.template import TemplateError  # noqa: E402

import make_fixtures  # noqa: E402  (tests/fixtures/bom/make_fixtures.py)

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
FIXTURES = os.path.join(ROOT, "tests", "fixtures", "bom")
NORMALIZED = os.path.join(FIXTURES, "normalized")
ARCHIVE = os.path.join(ROOT, "_archive", "SC-Sizing-main", "tests", "fixtures", "bom")
ARCHIVE_NORMALIZED = os.path.join(ARCHIVE, "normalized")

archive_only = pytest.mark.skipif(
    not os.path.isdir(ARCHIVE), reason="SC//Design archive fixtures not present (_archive is gitignored)")

LOAD_BEARING = ("cpu", "memory", "storage", "controller", "nic", "boss", "chassis")


def _load(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


# ─── synthetic fixtures: detection + exact normalized equality ───────────────

SYNTHETIC = [(name, fmt) for name, _builder, fmt in make_fixtures.FIXTURES]


@pytest.mark.parametrize("name,fmt", SYNTHETIC)
def test_synthetic_fixture_detected(name, fmt):
    path = os.path.join(FIXTURES, name)
    assert detect_format(path, name) == fmt
    assert fmt in FORMAT_LABELS


@pytest.mark.parametrize("name,fmt", SYNTHETIC)
def test_synthetic_fixture_parses_to_reviewed_normalized(name, fmt):
    path = os.path.join(FIXTURES, name)
    bom, got_fmt = parse_file(path, name)
    assert got_fmt == fmt
    expected = _load(os.path.join(NORMALIZED, name + ".json"))
    assert bom.to_dict() == expected
    # and the reviewed JSON survives our own lenient from_dict unchanged
    assert NormalizedBOM.from_dict(expected).to_dict() == expected


def test_every_synthetic_fixture_has_an_expectation():
    files = sorted(f for f in os.listdir(FIXTURES) if f.startswith("synthetic_"))
    assert files == sorted(n for n, _ in SYNTHETIC)
    assert sorted(os.listdir(NORMALIZED)) == sorted(n + ".json" for n, _ in SYNTHETIC)


@pytest.mark.parametrize("name", ["not_a_bom.xlsx", "not_a_bom.csv"])
def test_not_a_bom_is_unrecognized(name):
    path = os.path.join(FIXTURES, name)
    assert detect_format(path, name) is None
    with pytest.raises(UnrecognizedFormat) as exc:
        parse_file(path, name)
    assert "template" in exc.value.hint


def test_pdf_is_not_detected(tmp_path):
    pdf = tmp_path / "quote.pdf"
    pdf.write_bytes(b"%PDF-1.4\n%synthetic\n")
    assert detect_format(str(pdf), "quote.pdf") is None
    with pytest.raises(UnrecognizedFormat) as exc:
        parse_file(str(pdf), "quote.pdf")
    assert "Only .xlsx and .csv" in exc.value.hint


def test_wrong_magic_bytes_are_unrecognized(tmp_path):
    fake = tmp_path / "quote.xlsx"
    fake.write_text("SKU,Description,Qty\n210-BDZY,PowerEdge R760 Server,1\n")
    assert detect_format(str(fake), "quote.xlsx") is None
    with pytest.raises(UnrecognizedFormat):
        parse_file(str(fake), "quote.xlsx")
    # a real workbook under a .csv name is not a service-tag export either
    xlsx_as_csv = tmp_path / "quote.csv"
    xlsx_as_csv.write_bytes(open(os.path.join(FIXTURES, "synthetic_dell_quote.xlsx"), "rb").read())
    assert detect_format(str(xlsx_as_csv), "quote.csv") is None


def test_synthetic_details_that_matter():
    """Spot checks on the reviewed expectations, so a regenerated JSON that
    silently changed one of these would be noticed in review."""
    dcsc = _load(os.path.join(NORMALIZED, "synthetic_lenovo_dcsc.xlsx.json"))
    prod, dr = dcsc["configs"]
    assert (prod["name"], prod["nodeCount"]) == ("Acme PROD", 3)
    assert (dr["name"], dr["nodeCount"]) == ("Acme DR", 1)
    by_part = {c["partNumber"]: c for c in prod["components"]}
    assert by_part["Z008"]["quantity"] == 6                 # duplicate feature-code rows summed
    assert by_part["SC7H"]["category"] == "other"           # software block folded into the machine
    assert "Z014" not in by_part and "Z017" not in by_part  # dummies / XClarity dropped
    assert "QA0Y" not in by_part                            # service block dropped wholesale
    assert by_part["5977"]["category"] == "other"           # absence line kept

    boss = _load(os.path.join(NORMALIZED, "synthetic_lenovo_dcsc_boss.xlsx.json"))["configs"][0]
    cats = {c["partNumber"]: c["category"] for c in boss["components"]}
    assert cats["Z204"] == "boss" and cats["Z205"] == "other" and cats["Z206"] == "storage"

    csv_bom = _load(os.path.join(NORMALIZED, "synthetic_dell_servicetag.csv.json"))
    xlsx_bom = _load(os.path.join(NORMALIZED, "synthetic_dell_servicetag.xlsx.json"))
    assert csv_bom["configs"][0]["name"] == "Config 1"
    assert xlsx_bom["configs"][0]["name"] == "ABC1234"
    assert csv_bom["configs"][0]["components"] == xlsx_bom["configs"][0]["components"]
    st = {c["partNumber"]: c for c in csv_bom["configs"][0]["components"]}
    assert st["400-BKGJ"]["quantity"] == 3 and st["161-BCPX"]["quantity"] == 9
    assert st["338-CPBV"]["quantity"] == 2 and st["370-BBRY"]["quantity"] == 16
    assert st["403-BCID"] == {"partNumber": "403-BCID", "description": "No BOSS Card",
                              "quantity": 1, "category": "other"}
    assert "370-ABWF" not in st                              # 'DIMM Blanks for …' dropped, not a CPU
    assert st["321-BGZI"]["description"] == (
        '2.5" Chassis with up to 16 NVMe Drives, Dual Controller, RAID Config')

    quote = _load(os.path.join(NORMALIZED, "synthetic_dell_quote.xlsx.json"))
    assert [(c["name"], c["nodeCount"]) for c in quote["configs"]] == [("Production", 3), ("Disaster Recovery", 1)]
    q = {c["partNumber"]: c["quantity"] for c in quote["configs"][0]["components"]}
    assert q["338-CPBV"] == 6 and q["370-BBRY"] == 96 and "892-9155" not in q and "370-BCCX" not in q

    lists = _load(os.path.join(NORMALIZED, "synthetic_dell_lists.xlsx.json"))
    r660 = {c["partNumber"]: c for c in lists["configs"][0]["components"]}
    assert r660["HMCG78AEBRA107N"]["quantity"] == 24        # 8x per node × QTY 3, PN prefix stripped
    assert r660["HMCG78AEBRA107N"]["description"] == "16GB RDIMM, 5600MT/s, Single Rank"
    assert r660["325-BEVE"]["quantity"] == 3                # first of a comma list
    assert lists["configs"][1]["serverModel"] == "PowerEdge R750XS"

    cols = _load(os.path.join(NORMALIZED, "synthetic_dell_columns.xlsx.json"))
    c1 = cols["configs"][0]
    assert c1["nodeCount"] == 3 and c1["components"][0] == {
        "partNumber": None, "description": "PowerEdge R660xs", "quantity": 3, "category": "chassis"}
    assert [c["quantity"] for c in c1["components"] if c["category"] == "cpu"] == [6]

    vnet = _load(os.path.join(NORMALIZED, "synthetic_dell_vnet.xlsx.json"))["configs"][0]
    v = {c["partNumber"]: c for c in vnet["components"]}
    assert v["338-CPBV"]["quantity"] == 2 and v["490-BJIT"]["category"] == "gpu"
    assert v["770-BDRQ"]["category"] == "other" and "770-BEKK" not in v
    assert "370-BBRX" not in v and "343-BBST" not in v


# ─── template ─────────────────────────────────────────────────────────────────

def _write(tmp_path, name, data):
    path = tmp_path / name
    path.write_bytes(data)
    return str(path)


def _edited_template(tmp_path, name, rows, header=None):
    """Our blank template with rows appended (and optionally a tampered
    header), saved through openpyxl the way a user's spreadsheet tool would."""
    wb = load_workbook(io.BytesIO(template.build_template_bytes()))
    ws = wb[template.SHEET]
    if header is not None:
        for i, value in enumerate(header, start=1):
            ws.cell(row=1, column=i).value = value
    for row in rows:
        ws.append(row)
    buf = io.BytesIO()
    wb.save(buf)
    return _write(tmp_path, name, buf.getvalue())


def test_template_round_trip_including_node_count(tmp_path):
    source = make_fixtures.supermicro_bom()
    path = _write(tmp_path, "sc-bom-template.xlsx", template.build_template_bytes(source))
    assert detect_format(path, "sc-bom-template.xlsx") == "template"
    bom, fmt = parse_file(path, "sc-bom-template.xlsx")
    assert fmt == "template"
    expected = source.to_dict()
    expected["rawText"] = bom.raw_text
    assert bom.to_dict() == expected
    assert bom.configs[0].node_count == 3
    assert bom.vendor == "Supermicro"
    assert detect_vendor(bom) == "Supermicro"
    # and it is byte-identical in content to the committed fixture's parse
    committed = _load(os.path.join(NORMALIZED, "synthetic_template.xlsx.json"))
    assert bom.to_dict() == committed


def test_template_two_configs_keep_first_seen_order(tmp_path):
    path = _edited_template(tmp_path, "t.xlsx", [
        ["DR", "PowerEdge R760", "Dell", "210-BDZY", "PowerEdge R760 Server", 1, "chassis", 1],
        ["Prod", "PowerEdge R760", "Dell", "210-BDZY", "PowerEdge R760 Server", 3, "chassis", 3],
        ["DR", "", "", "338-CPBV", "Intel Xeon Gold 6526Y", 2, "CPU", None],
        ["Prod", "", "", "338-CPBV", "Intel Xeon Gold 6526Y", "6", "cpu", None],
    ])
    bom, _ = parse_file(path, "t.xlsx")
    assert [(c.name, c.server_model, c.node_count, len(c.components)) for c in bom.configs] == [
        ("DR", "PowerEdge R760", 1, 2), ("Prod", "PowerEdge R760", 3, 2)]
    assert bom.configs[1].components[1].quantity == 6
    assert bom.configs[0].components[1].category == "cpu"      # case-insensitive category


def test_template_strict_errors_list_every_bad_row(tmp_path):
    path = _edited_template(tmp_path, "bad.xlsx", [
        ["Config 1", "PowerEdge R760", "Dell", "210-BDZY", "PowerEdge R760 Server", 1, "chassis"],
        ["Config 1", "", "Dell", "400-BKGJ", "3.84TB NVMe drive", 3, "disk"],           # row 3
        ["Config 1", "", "Dell", "370-BBRY", "32GB RDIMM", 2.5, "memory"],              # row 4
        ["Config 1", "", "Dell", "338-CPBV", "Intel Xeon Gold 6526Y", None, "cpu"],     # row 5
        ["Config 1", "", "Dell", "540-BCXW", "", 1, "nic"],                             # row 6
        ["Config 1", "", "Acme", "405-AAZF", "Dell HBA355i", 1, "controller"],          # row 7
        ["Config 1", "", "Dell", "450-AKYB", "Power supply", 0, "other"],               # row 8
    ])
    assert detect_format(path, "bad.xlsx") == "template"
    with pytest.raises(TemplateError) as exc:
        parse_file(path, "bad.xlsx")
    errors = exc.value.errors
    assert any(e.startswith("Row 3:") and "Category" in e and "'disk'" in e for e in errors)
    assert any(e.startswith("Row 4:") and "Quantity" in e and "whole number" in e for e in errors)
    assert any(e.startswith("Row 5:") and "Quantity is required" in e for e in errors)
    assert any(e.startswith("Row 6:") and "Description is required" in e for e in errors)
    assert any(e.startswith("Row 7:") and "Vendor" in e and "'Acme'" in e for e in errors)
    assert any(e.startswith("Row 8:") and "Quantity" in e for e in errors)
    assert not any(e.startswith("Row 2:") for e in errors)
    assert "; ".join(errors) == str(exc.value)


def test_template_nodes_column_is_validated(tmp_path):
    path = _edited_template(tmp_path, "nodes.xlsx", [
        ["C1", "PowerEdge R760", "Dell", "210-BDZY", "PowerEdge R760 Server", 3, "chassis", 3],
        ["C1", "", "Dell", "338-CPBV", "Intel Xeon Gold 6526Y", 6, "cpu", 4],          # conflicts
        ["C2", "", "Dell", "210-BDZY", "PowerEdge R760 Server", 1, "chassis", "two"],   # not a number
    ])
    with pytest.raises(TemplateError) as exc:
        parse_file(path, "nodes.xlsx")
    errors = exc.value.errors
    assert any(e.startswith("Row 3:") and "Nodes" in e and "conflicts" in e for e in errors)
    assert any(e.startswith("Row 4:") and "Nodes" in e and "whole number" in e for e in errors)


def test_template_empty_sheet_is_an_error(tmp_path):
    path = _write(tmp_path, "empty.xlsx", template.build_template_bytes())
    with pytest.raises(TemplateError) as exc:
        parse_file(path, "empty.xlsx")
    assert exc.value.errors == ["The BOM sheet has no line items."]


def test_template_header_mismatch(tmp_path):
    # Our marker is present (defined name) but the header was edited: the
    # ladder still says 'template' and the strict parser reports row 1.
    path = _edited_template(tmp_path, "hdr.xlsx", [
        ["C1", "", "Dell", "210-BDZY", "PowerEdge R760 Server", 1, "chassis"]],
        header=["Config", "Model", "Vendor", "Part", "Description", "Qty", "Category"])
    assert detect_format(path, "hdr.xlsx") == "template"
    with pytest.raises(TemplateError) as exc:
        parse_file(path, "hdr.xlsx")
    assert exc.value.errors[0].startswith("Row 1: header must be exactly")
    # An 8th column other than Nodes is refused too.
    path = _edited_template(tmp_path, "col8.xlsx", [], header=template.COLUMNS + ["Price"])
    with pytest.raises(TemplateError) as exc:
        template.parse_template(path)
    assert "8th column" in exc.value.errors[0]
    # No marker and no exact header: not our template, nothing else matches.
    wb = Workbook()
    ws = wb.active
    ws.title = "BOM"
    ws.append(["Config", "Model", "Vendor", "Part", "Description", "Qty", "Category"])
    ws.append(["C1", "", "Dell", "210-BDZY", "PowerEdge R760 Server", 1, "chassis"])
    buf = io.BytesIO()
    wb.save(buf)
    path = _write(tmp_path, "nomarker.xlsx", buf.getvalue())
    assert detect_format(path, "nomarker.xlsx") is None
    with pytest.raises(UnrecognizedFormat):
        parse_file(path, "nomarker.xlsx")
    # The exact header alone (marker lost in a re-save) still counts as ours.
    ws.delete_rows(1)
    ws.insert_rows(1)
    for i, label in enumerate(template.COLUMNS, start=1):
        ws.cell(row=1, column=i).value = label
    buf = io.BytesIO()
    wb.save(buf)
    path = _write(tmp_path, "headeronly.xlsx", buf.getvalue())
    assert detect_format(path, "headeronly.xlsx") == "template"


def test_template_blank_vendor_and_config_default(tmp_path):
    path = _edited_template(tmp_path, "vendor.xlsx", [
        [None, "SYS-511R-M", None, "511R-M-OTO-17", "UP 1U Optimized System", 3, "chassis"],
        [None, None, "unknown", "P4X-UPE2434-SRMXC", "Intel Xeon E-2434", 3, "cpu"],
    ])
    # The strict parser itself never guesses (build spec §9): blank -> Unknown.
    raw = template.parse_template(path)
    assert raw.vendor == "Unknown"
    assert [c.name for c in raw.configs] == ["Config 1"]
    assert raw.configs[0].server_model == "SYS-511R-M"
    assert raw.configs[0].node_count is None
    assert detect_vendor(raw) == "Supermicro"          # content still says Supermicro
    # Finding: "Template uploads with a blank Vendor column stay 'Unknown' —
    # parsers.detect_vendor exists but is never called". parse_file now wires
    # detect_vendor in when the template's Vendor column is blank.
    bom, fmt = parse_file(path, "vendor.xlsx")
    assert fmt == "template"
    assert bom.vendor == "Supermicro"


def test_dell_list_qty_desc_pn_tolerates_non_numeric_quantity(tmp_path):
    # Finding: "QTY/Description/Part Number list parser crashes on a
    # non-numeric quantity cell" — '2 ea' / 'TBD' must coerce to the default
    # like every other parser, never raise ValueError into the generic
    # 'could not process the file' route message.
    wb = Workbook()
    ws = wb.active
    ws.append(["QTY", None, "Description", "Part Number"])
    ws.append([3, None, "PowerEdge R760 Server", "210-BDZY"])
    ws.append(["2 ea", None, "3.84TB NVMe Read Intensive SSD", "DMF5Y"])
    ws.append(["TBD", None, "32GB RDIMM, 5600MT/s, Dual Rank", "1V1N1"])
    buf = io.BytesIO()
    wb.save(buf)
    path = _write(tmp_path, "list.xlsx", buf.getvalue())
    assert detect_format(path, "list.xlsx") == "dell_list_qty_desc_pn"
    bom, fmt = parse_file(path, "list.xlsx")
    assert fmt == "dell_list_qty_desc_pn"
    qty = {c.description: c.quantity for c in bom.configs[0].components}
    assert qty["3.84TB NVMe Read Intensive SSD"] == 1
    assert qty["32GB RDIMM, 5600MT/s, Dual Rank"] == 1
    assert qty["PowerEdge R760 Server"] == 3


def test_xlsx_decompression_bomb_is_refused_before_openpyxl(tmp_path):
    # Finding: "xlsx decompression bomb: sharedStrings is loaded eagerly
    # before any row cap applies" — a sub-MB upload whose sharedStrings part
    # inflates past the member cap must be refused by the zip pre-check in
    # load_workbook_safe (and via parse_file / ai_prefill._xlsx_text), before
    # openpyxl materialises the strings.
    import zipfile
    from xlsx_utils import SheetTooLargeError
    from bom.parsers.common import load_workbook_safe
    from bom import ai_prefill
    path = str(tmp_path / "bomb.xlsx")
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", "<Types/>")
        zf.writestr("xl/sharedStrings.xml", b"<si>x</si>" * (6 * 1024 * 1024))  # 60 MB
    assert os.path.getsize(path) < 1024 * 1024, "the bomb passes the 10 MB upload cap"
    with pytest.raises(SheetTooLargeError):
        load_workbook_safe(path)
    with pytest.raises(SheetTooLargeError):
        parse_file(path, "bomb.xlsx")     # detect_format must not swallow it
    with pytest.raises(ai_prefill.PrefillError):
        ai_prefill._xlsx_text(path)


def test_zip_pre_check_lets_ordinary_workbooks_through():
    from bom.parsers.common import check_zip_bomb
    path = os.path.join(FIXTURES, "synthetic_lenovo_dcsc.xlsx")
    check_zip_bomb(path)                  # must not raise


def test_template_marker_and_validation_lists():
    wb = load_workbook(io.BytesIO(template.build_template_bytes()))
    assert template.DEFINED_NAME in wb.defined_names
    ws = wb[template.SHEET]
    assert ws["A1"].comment.text == template.MARKER_COMMENT
    assert [c.value for c in ws[1]] == template.ALL_COLUMNS
    assert ws.freeze_panes == "A2"
    formulas = sorted(dv.formula1 for dv in ws.data_validations.dataValidation)
    assert formulas == sorted(['"%s"' % ",".join(template.VENDORS), '"%s"' % ",".join(template.CATEGORIES)])
    assert template.INSTRUCTIONS_SHEET in wb.sheetnames


# ─── categorize / should_drop (survey §4) ─────────────────────────────────────

CATEGORY_CASES = [
    # §4 items 1-19 (LLM value → rule value, the survey's verdict)
    ("ThinkSystem SR630 V3 3yr Base Warranty", None),                                     # 1 dropped
    ("6400MT/s RDIMMs", None),                                                            # 2 dropped
    ("5600MT/s RDIMMs", None),
    ("PowerEdge R660xs Motherboard with Broadcom 5720 Dual Port 1Gb On-Board LOM", "nic"),  # 3
    ("R750 Motherboard with Broadcom 5720 Dual Port 1Gb On-Board LOM", "nic"),
    ("PowerEdge R760 Motherboard with ONLY CPUs below 250W supported, MLK", "other"),
    ('ThinkSystem 1U V3 10x2.5" Media Bay w/ Ext. Diagnostics Port', "chassis"),         # 4
    ("ThinkSystem M.2 VA 480GB Read Intensive NVMe PCIe 4.0 x4 NHS SSD", "storage"),     # 5 (+ M.2 flag)
    ("SR650 V4/SR630 V4 x16 OCP Cable Kit", "other"),                                    # 6
    ("ThinkSystem SR650 V4 Processor Board", "other"),                                   # 7
    ("ThinkSystem V4 CPU HS Clip", "other"),
    ("Heatsink for 2 CPU configuration (CPU greater than 165W)", "other"),               # 8
    ("Heatsink for 2 CPU configuration (CPU ≤150W)", "other"),                      # 9
    ("Trusted Platform Module 2.0 V6", "other"),                                         # 10
    ("TPM 2.0 with Secure Boot", "other"),
    ("Dell 2U Cable Management Arm Kit", "other"),                                       # 11
    ("Cable Management Arm", "other"),
    ("Intel X710 2-port 10GBase-T", "nic"),                                              # 12
    ("Dell Intel X710 Dual Port 10GB Base-T OCP 3.0", "nic"),
    ('ThinkSystem 2U V4 Rear 4x2.5" NVMe Gen5 Backplane', "chassis"),                    # 13
    ("PowerEdge R660xs", "chassis"),                                                     # 14
    ("PowerEdge R760 Server", "chassis"),
    ("UP 1U X13SCH-SYS, CSE-813MF2TS-R0RCNBP, PWS-602A-1R Optimized System", "chassis"),  # 15
    ('2.5" HDD Tray in 4th Generation 3.5" Hot Swap Tray', "other"),
    ('SSD 2.5" SATA 1.9TB >1DWPD TLC, 7mm', "storage"),
    ("8-port 12Gb/s SAS3 HBA, PCIe x8 Gen4, Low Profile", "controller"),                 # 16
    ("Dell HBA355I Controller PCI Full Height", "controller"),                           # 17
    ("8GB SD Card for RIPS", "other"),                                                   # 18
    ("Internal Dual SD Module", "other"),
    ("DVD ROM SATA Internal", "other"),
    ("Dell iDRAC 9 Enterprise Digital License, 15G", "other"),                           # 19
    ("XClarity Pro - 3 Years", None),
    ("5Yr Standard NBD Resp + KYD", "other"),
    # ordering notes from §4
    ("Memory Dummy", None),
    ("HDD Filler", None),
    ("HDD Type Label", None),
    ("SAS Cable", "other"),
    ("OCP3.0 Filler", None),
    ("Custom Label (NIC)", None),
    ("440-16i SAS/SATA PCIe Gen4 12Gb HBA Placement", None),
    ("Front PERC Mechanical Parts", "other"),
    ("Bracket,PERC9", "other"),
    ("Power Saving Dell Active Power Controller", None),
    ("Chassis with up to 12 SAS/SATA Drives, LP Adapter PERC 11", "chassis"),
    ('2.5" Chassis with up to 16 NVMe Drives, Dual Controller, RAID Config', "chassis"),
    ("ThinkSystem SR630 V3 MCIO8x flat 2in1 CBL from PCIe1/2 to 4NVMe BP, 1P", "other"),
    ("DIMM Blanks for System with 1 Processor", None),
    ("Blank for 1CPU Configuration", None),
    # the real hardware lines
    ("ThinkSystem 440-16i SAS/SATA PCIe Gen4 12Gb HBA", "controller"),
    ("Dell HBA355i Adapter, Low Profile", "controller"),
    ("PERC H755N Front", "controller"),
    ("ThinkSystem M.2 RAID B540p-2HS SATA/NVMe Adapter", "boss"),
    ("BOSS-N1 controller card + with 2 M.2 480GB (RAID 1)", "boss"),
    ("BOSS controller card + with 2 M.2 Sticks 480GB (RAID 1),FH", "boss"),
    ("NVIDIA L4 24GB PCIe", "gpu"),
    ("Intel Xeon Gold 6526Y 2.8G, 16C/32T, 20GT/s, 37.5M Cache, Turbo, HT (195W) DDR5-5200", "cpu"),
    ("Intel Xeon 6517P 16C 190W 3.2GHz Processor", "cpu"),
    ("AMD EPYC 9124 3.0G, 16C/32T", "cpu"),
    ("32GB RDIMM, 5600MT/s, Dual Rank", "memory"),
    ("ThinkSystem 32GB TruDDR5 6400MHz (2Rx8) RDIMM", "memory"),
    ("3.84TB Enterprise NVMe Read Intensive AG Drive U.2 Gen4 Flex Bay", "storage"),
    ("8TB Hard Drive SAS 12Gbps 7.2K 512e 3.5in Hot-Plug, AG Drive", "storage"),
    ("3.84TB NVMe SAS Read Intensive SSD", "storage"),
    ("Intel E810-XXV Dual Port 10/25GbE SFP28, OCP NIC 3.0", "nic"),
    ("Broadcom 5720 Quad Port 1GbE BASE-T, rNDC", "nic"),
    ("ThinkSystem Broadcom 57504 10/25GbE SFP28 4-Port OCP Ethernet Adapter", "nic"),
    ("ThinkSystem SR650 V4 12x3.5\" SAS/SATA + 4x AnyBay Backplane", "chassis"),
    ("Dell R750XS 12x 3.5in LFF, Riser 4 Config", "chassis"),
    # pt-BR DCSC
    ("Processador Intel Xeon 6505P 12C 150 W 2,2 GHz", "cpu"),
    ("RDIMM ThinkSystem de 16 GB TruDDR5 6.400 MHz (1Rx8)", "memory"),
    ("HBA ThinkSystem 440-16i SAS/SATA PCIe Gen4 12 Gb", "controller"),
    ('Unidade de estado sólido HS ThinkSystem 2,5" U.2 VA 3,84 TB de uso intenso de leitura NVMe PCIe 5.0 x4',
     "storage"),
    ("Unidade de disco rígido hot-swap 512e ThinkSystem 3,5 pol. 12 TB 7,2K SAS 12 Gb v2", "storage"),
    ("Adaptador Ethernet ThinkSystem Broadcom 57504 10/25 GbE SFP28 de 4 Portas PCIe", "nic"),
    ('Chassi ThinkSystem SR650 V4 de 2,5" 24 compartimentos', "chassis"),
    ("Fonte de alimentação hot-swap ThinkSystem 1100 W 230 V Titanium v4", "other"),
    ("Preenchimento de HDD ThinkSystem de 3,5\"", None),
    ("Etiqueta de tipo de HDD", None),
    ("Apenas registro", None),
]

NEGATED_CASES = [
    "No BOSS Card", "BOSS Blank", "LOM Blank", "No RAID", "Assembly BOSS Blank",
    "No Controller", "No HBA", "No Additional Processor", "No OCP", "Riser Blank",
    "C1, No RAID for HDDs/SSDs", "Unconfigured RAID",
    "Select Storage devices - no configured RAID required",
    "Dispositivos de armazenamento - nenhum RAID configurado necessário",
]


@pytest.mark.parametrize("description,expected", CATEGORY_CASES)
def test_categorize_survey_cases(description, expected):
    if expected is None:
        assert should_drop(description), "expected %r to be dropped" % description
    else:
        assert not should_drop(description), "expected %r to be kept" % description
        assert categorize(description) == expected


@pytest.mark.parametrize("description", NEGATED_CASES)
def test_negated_indicators_are_kept_as_other(description):
    assert is_absence(description)
    assert not should_drop(description)
    assert categorize(description) == "other"


def test_negated_lines_never_count_as_hardware_even_with_keywords():
    # 'No BOSS Card' contains BOSS, 'LOM Blank' contains LOM, 'No RAID' would hit nothing
    # but 'No HBA' contains HBA — all must stay 'other'.
    for text in ("No BOSS Card", "LOM Blank", "No HBA", "No Controller", "No Power Cord",
                 "No Cables Required", "None Required"):
        assert categorize(text) == "other"


def test_drop_by_dell_sku_family():
    assert should_drop("Basic Deployment, Dell Server", "883-BBFN")
    assert should_drop("ProSupport Plus 4-Hour Mission Critical, 3 Years", "892-9155")
    assert should_drop("Anything at all", "379-BDSX")
    assert not should_drop("PowerEdge R760 Server", "210-BDZY")
    assert not should_drop("No BOSS Card", "403-BCID")          # absence wins over everything
    assert should_drop("", "210-BDZY") and should_drop(None)


def test_m2_media_flag():
    assert is_m2_media("ThinkSystem M.2 VA 480GB Read Intensive NVMe PCIe 4.0 x4 NHS SSD")
    assert not is_m2_media("ThinkSystem 2.5\" U.2 VA 3.84TB Read Intensive NVMe PCIe 5.0 x4 HS SSD")


def test_split_nx_and_server_model():
    assert split_nx("8x 16GB RDIMM, 4800MT/s, Dual Rank") == (8, "16GB RDIMM, 4800MT/s, Dual Rank")
    assert split_nx("4 X 3.84TB NVMe") == (4, "3.84TB NVMe")
    assert split_nx("Dell HBA355i Front") == (1, "Dell HBA355i Front")
    assert split_nx("x16 OCP Cable Kit") == (1, "x16 OCP Cable Kit")
    assert server_model_from_text("Server : ThinkSystem SR650 V4-3yr Base Warranty") == "ThinkSystem SR650 V4"
    assert server_model_from_text("Scale Computing Platform SR630 V3") == "ThinkSystem SR630 V3"
    assert server_model_from_text("PowerEdge R760 Server") == "PowerEdge R760"
    assert server_model_from_text("Dell R750XS 12x 3.5in LFF") == "PowerEdge R750XS"
    assert server_model_from_text("HPE ProLiant DL380 Gen11") == "ProLiant DL380 Gen11"
    assert server_model_from_text("SYS-511R-M") == "SYS-511R-M"
    assert server_model_from_text("Scale Computing Software") is None
    assert server_model_from_text(None) is None


# ─── Dell 30-character de-wrap (survey §3.2) ──────────────────────────────────

DEWRAP_CASES = [
    # (wrapped text as exported, original) — taken from the archived exports
    ("UEFI BIOS Boot Mode with GPT P artition", "UEFI BIOS Boot Mode with GPT Partition"),
    ("Dual, Hot-plug, Redundant Powe r Supply (1+1), 1100W AC",
     "Dual, Hot-plug, Redundant Power Supply (1+1), 1100W AC"),
    ("Broadcom 5720 Quad Port 1GbE B ASE-T, rNDC", "Broadcom 5720 Quad Port 1GbE BASE-T, rNDC"),
    ("PERC H730 Integrated RAID Cont roller, 1GB Cache", "PERC H730 Integrated RAID Controller, 1GB Cache"),
    ("1.6TB Solid State Drive SATA M ix Use MLC 6Gbps 512n 2.5in Ho t-plug Drive, Hawk-M4E",
     "1.6TB Solid State Drive SATA Mix Use MLC 6Gbps 512n 2.5in Hot-plug Drive, Hawk-M4E"),
    ("Power Cord - NEMA 5-15P to C13 , 3M, 125V, 15A (North America , Guam, North Marianas, Philip pines, Samoa, Vietnam)",
     "Power Cord - NEMA 5-15P to C13, 3M, 125V, 15A (North America, Guam, North Marianas, Philippines, Samoa, Vietnam)"),
    ("Intel Xeon Gold 6240 2.6G, 18C /36T, 10.4GT/s, 24.75M Cache, Turbo, HT (150W) DDR4-2933",
     "Intel Xeon Gold 6240 2.6G, 18C/36T, 10.4GT/s, 24.75M Cache, Turbo, HT (150W) DDR4-2933"),
    ("Intel Xeon Silver 4310 2.1G, 1 2C/24T, 10.4GT/s, 18M Cache, T urbo, HT (120W) DDR4-2666",
     "Intel Xeon Silver 4310 2.1G, 12C/24T, 10.4GT/s, 18M Cache, Turbo, HT (120W) DDR4-2666"),
    ('2.5" Chassis with up to 16 NVM e Drives, Dual Controller, RAI D Config',
     '2.5" Chassis with up to 16 NVMe Drives, Dual Controller, RAID Config'),
    # the chunk started with a space in the original: the double space collapses
    ("Broadcom 57416 Dual Port 10GbE  BASE-T & 5720 Dual Port 1GbE BASE-T, rNDC",
     "Broadcom 57416 Dual Port 10GbE BASE-T & 5720 Dual Port 1GbE BASE-T, rNDC"),
    # the chunk ended in a space in the original: the join space IS that space
    ("12TB 7.2K RPM SAS 12Gbps 512e 3.5in Internal Hard Drive",
     "12TB 7.2K RPM SAS 12Gbps 512e 3.5in Internal Hard Drive"),
    ("32GB RDIMM, 2400MT/s, Dual Ran k, x4 Data Width", "32GB RDIMM, 2400MT/s, Dual Rank, x4 Data Width"),
    # untouched: short, and an original double space inside a chunk
    ("No RAID", "No RAID"),
    ("PowerEdge R740 CCC and BIS Mar king,  No CE Marking", "PowerEdge R740 CCC and BIS Marking,  No CE Marking"),
    ("", ""),
]


@pytest.mark.parametrize("wrapped,original", DEWRAP_CASES)
def test_dewrap_dell(wrapped, original):
    assert dewrap_dell(wrapped) == original


@pytest.mark.parametrize("original", [
    "Intel E810-XXV Dual Port 10/25GbE SFP28, OCP NIC 3.0",
    "Dual, Hot Plug, Power Supply (1+1) Redundant 1400W 2U",
    "Dell HBA355i Adapter, Low Profile",
    "8TB Hard Drive SAS 12Gbps 7.2K 512e 3.5in Hot-Plug, AG Drive",
    "PowerEdge R760 Motherboard with Broadcom 5720 Dual Port 1Gb On-Board LOM",
    "3.84TB Enterprise NVMe Read Intensive AG Drive U.2 Gen4 Flex Bay",
    "x" * 30, "x" * 31, "x" * 60 + " tail", "a" * 29 + " " + "b" * 40,
])
def test_dewrap_inverts_the_exporter_wrap(original):
    assert dewrap_dell(make_fixtures.wrap30(original)) == original


# ─── quantity coercion ────────────────────────────────────────────────────────

@pytest.mark.parametrize("value,expected", [
    (3, 3), (3.0, 3), ("3", 3), ("3,0", 3), (" 3 ", 3), ("3.0", 3), ("\xa03\xa0", 3),
    (0, 0), (-2, -2), (2.9, 2), ("96", 96),
    (None, 1), ("", 1), ("   ", 1), ("abc", 1), ("No charge", 1), (True, 1), (False, 1),
    (float("nan"), 1), (float("inf"), 1),
])
def test_to_int(value, expected):
    assert to_int(value) == expected


def test_to_int_default_is_honoured():
    assert to_int(None, default=0) == 0
    assert to_int("n/a", default=7) == 7
    assert to_int(True, default=0) == 0


@pytest.mark.parametrize("value,expected", [
    (None, ""), (3.0, "3"), (3, "3"), (2.5, "2.5"), (" Qty\xa0", "Qty"), (True, "True"),
    (8123.0, "8123"), (float("nan"), "nan"),
])
def test_s(value, expected):
    assert s(value) == expected


# ─── archive-optional parity with SC//Design's normalized JSON ───────────────

ARCHIVE_FILES = {
    # original filename -> (format, [(config name, server model, node count), ...])
    "03172026-MCCC-3SR650V4-Scale_O1-2x24C-125TBR-10_25GbE-3YP247-KKanji.xlsx": (
        "lenovo_dcsc", [("Scale Cluster Server Node -- 2x24C-41.76TB Raw", "ThinkSystem SR650 V4", 3)]),
    "03192026-MCCC-4SR650V4-Scale_O2-2x16C-167TBR-10_25GbE-3YP247-KKanji.xlsx": (
        "lenovo_dcsc", [("Scale Cluster Server Node -- 2x16C - 41.76TB Raw", "ThinkSystem SR650 V4", 4)]),
    "2026-03-13-Frazier-3SR650V4-Scale-466.5TBR-NVMe+HDD-3YP247-KKanji.xlsx": (
        "lenovo_dcsc", [("Scale Server Node -  155.5TBRaw - 9x16TBSAS+3x3,84TBNVMeAnyBay backplane",
                         "ThinkSystem SR650 V4", 3)]),
    "Arrow_SR650V4_x3_TCE__5Y-NBD_v1_17-03-2026.xlsx": (
        "lenovo_dcsc", [("HC3650F", "ThinkSystem SR650 V4", 3)]),
    "Example HC5650D_Lenovo(2x6505P_16x16GB_3x3.84TB+9x2TB_SFP28).xlsx": (
        "lenovo_dcsc", [("Config 1", "ThinkSystem SR650 V4", 1)]),
    "Floyd County Public Schools SR630 V3 For SCALE 20260217.xlsx": (
        "lenovo_dcsc", [("Config 1", "ThinkSystem SR630 V3", 3)]),
    "MASP - SR650V4.xlsx": (
        "lenovo_dcsc", [("Config 1", "ThinkSystem SR650 V4", 3)]),
    "SlingerSD-BOM-VMwareReplacement-LenovoScale-20260316.xlsx": (
        "lenovo_dcsc", [("Slinger SD Lenovo Scale PROD", "ThinkSystem SR630 V3", 3),
                        ("Slinger SD Lenovo Scale DR", "ThinkSystem SR630 V3", 1)]),
    "Snook ISD 31926.xlsx": (
        "lenovo_dcsc", [("Config 1", "ThinkSystem SR650 V4", 3)]),
    "2K7WWK2.csv": ("dell_service_tag", [("Config 1", "PowerEdge R730", 1)]),
    "3MJ2WM3.csv": ("dell_service_tag", [("Config 1", "PowerEdge R740XD", 1)]),
    "IFF+R750.xlsx": ("dell_service_tag", [("54G58Y3", "PowerEdge R750", 1)]),
    "3000200444800.2.xlsx": (
        "dell_quote", [("Production", "PowerEdge R760", 3), ("Disaster Recovery", "PowerEdge R760", 1)]),
    "3000200479140.1.xlsx": ("dell_quote", [("PowerEdge R660xs - 1450v", "PowerEdge R660xs", 1)]),
    "3000200479142.1.xlsx": (
        "dell_quote", [("PowerEdge R660xs - Qty 1 needed| Dual 8c| x16 16GB RAM| x3 12TB HDD",
                        "PowerEdge R660xs", 1)]),
    "CLUTCH Quote_611179-88827-00_3000200346871_3243700000_20260317_.xlsx": (
        "dh_bid", [("Config 1", "PowerEdge R760", 1), ("Config 2", "PowerEdge R760", 1)]),
    "ErieCountyConventionCenter_VNET_Cfg01.xlsx": ("dell_vnet", [("Config 1", "PowerEdge R760", 1)]),
    "AFCO Configurations 342026.xlsx": ("dell_list_sku", [("Config 1", "PowerEdge R660", 3)]),
    "Additional AFCO Configurations.xlsx": (
        "dell_list_sku", [("Config 1 - R660", "PowerEdge R660", 1), ("Config 2 - R750XS", "PowerEdge R750XS", 1)]),
    "AFCO Configurations.xlsx": (
        "dell_list_columns", [("Config 1", "PowerEdge R660xs", 3), ("Config 2", "PowerEdge R660", 3)]),
}

# Per file: the (category, part number, quantity) tuples we emit that
# SC//Design's normalized JSON does not ('extra'), and the ones it has that we
# do not ('missing'), on the load-bearing categories. Every entry is a
# deliberate difference with its reason; anything not listed here is a
# regression.
_AFCO_COLUMNS_PER_NODE = [("chassis", None, 1), ("controller", None, 1), ("cpu", None, 2),
                          ("memory", None, 8), ("nic", None, 1), ("storage", None, 4)]
ACCEPTED_DEVIATIONS = {
    "3000200479140.1.xlsx": dict(
        extra=[], missing=[("memory", "370-BCCX", 1)],
        reason="'6400MT/s RDIMMs' is a speed-selector line, not memory; dropped on purpose (survey §4.2)"),
    "3000200479142.1.xlsx": dict(
        extra=[("nic", "329-BHOF", 1)], missing=[],
        reason="motherboard with on-board 5720 LOM kept as nic so the LOM info finding fires (survey §4.3); "
               "the LLM called it 'other' in this file only"),
    "3MJ2WM3.csv": dict(
        extra=[("boss", "403-BCHJ", 2)], missing=[("boss", "403-BCHJ", 1)],
        reason="BOSS group quantity comes from its pieces: two M.2 sticks (7RKD7 x2) -> 2; a BOSS card is a "
               "boolean for the rules, so the count is harmless (survey §3.2)"),
    "AFCO Configurations 342026.xlsx": dict(
        extra=[("memory", "HMCG78AEBRA107N", 24), ("storage", "400-BMTN", 12)],
        missing=[("memory", None, 3), ("storage", "400-BMTN", 3)],
        reason="the LLM applied 'QTY 3' to every line and left '8x'/'4x' in the description; we emit "
               "N x 3 nodes and strip the '(Dell - Hynix PN)' prefix (survey §3.6: the LLM output is wrong)"),
    "AFCO Configurations.xlsx": dict(
        extra=[(c, p, q * 3) for c, p, q in _AFCO_COLUMNS_PER_NODE] * 2,
        missing=_AFCO_COLUMNS_PER_NODE * 2,
        reason="quantities are totals across the 3 nodes of each column (every other parser's convention); "
               "the LLM kept the per-node counts. The '3x PowerEdge R660xs' line itself (chassis, 3) matches"),
    "Additional AFCO Configurations.xlsx": dict(
        extra=[("chassis", "210-BEQQ", 1)], missing=[],
        reason="'PowerEdge R660 Server' base line kept as chassis (the LLM dropped it)"),
    "Arrow_SR650V4_x3_TCE__5Y-NBD_v1_17-03-2026.xlsx": dict(
        extra=[], missing=[("storage", "CBSZ", 6)],
        reason="M.2 480GB boot media next to the B540p adapter is not a data drive -> 'other' (survey §4.5)"),
    "CLUTCH Quote_611179-88827-00_3000200346871_3243700000_20260317_.xlsx": dict(
        extra=[("chassis", "210-BDZY", 1), ("chassis", "210-BDZY", 1)], missing=[],
        reason="the 'PowerEdge R760 Server' line of each config kept as chassis (the LLM dropped both)"),
    "Floyd County Public Schools SR630 V3 For SCALE 20260217.xlsx": dict(
        extra=[("chassis", "BQU6", 3)], missing=[("chassis", "7D73CTO1WW", 3)],
        reason="the CTO header row is the config, not a part (survey §4.1); the '1U 4x3.5\" Media Bay' "
               "line is chassis by the same rule that gave Slinger's BLKD 'Media Bay' chassis in the LLM output"),
    "IFF+R750.xlsx": dict(
        extra=[("chassis", "210-AYCG", 1), ("chassis", "321-BGZI", 2)], missing=[("chassis", "321-BGZI", 1)],
        reason="'PowerEdge R750 Server' base line kept as chassis; the chassis group's split backplane "
               "(YD2C2) and its cables are listed twice so the piece-sum rule gives 2 - node_count is 1 "
               "from the shape itself, so nothing downstream reads it"),
}


def _safe(name):
    return re.sub(r"[^\w.\-]", "_", name)


def _load_bearing(configs):
    """Multiset of (category, part number, quantity) over the load-bearing
    categories of a list of config dicts."""
    return Counter((c["category"], c["partNumber"], c["quantity"])
                   for cfg in configs for c in cfg["components"] if c["category"] in LOAD_BEARING)


@archive_only
def test_archive_lists_every_spreadsheet():
    present = sorted(f for f in os.listdir(ARCHIVE) if f.lower().endswith((".xlsx", ".csv")))
    assert present == sorted(ARCHIVE_FILES)


@archive_only
@pytest.mark.parametrize("filename", sorted(ARCHIVE_FILES))
def test_archive_fixture_parity(filename):
    fmt, configs = ARCHIVE_FILES[filename]
    path = os.path.join(ARCHIVE, filename)
    assert detect_format(path, filename) == fmt
    bom, got_fmt = parse_file(path, filename)
    assert got_fmt == fmt
    assert [(c.name, c.server_model, c.node_count) for c in bom.configs] == configs
    for cfg in bom.configs:
        assert cfg.components, "config %r has no components" % cfg.name
        for comp in cfg.components:
            assert comp.quantity >= 1 and comp.description
    ours = bom.to_dict()
    assert NormalizedBOM.from_dict(ours).to_dict() == ours

    ref_path = os.path.join(ARCHIVE_NORMALIZED, _safe(filename) + ".json")
    if not os.path.isfile(ref_path):
        assert filename.startswith("Example HC5650D"), "no reference JSON for %s" % filename
        return
    ref = _load(ref_path)
    assert bom.vendor == ref["vendor"]

    mine, theirs = _load_bearing(ours["configs"]), _load_bearing(ref["configs"])
    accepted = ACCEPTED_DEVIATIONS.get(filename, dict(extra=[], missing=[]))
    extra, missing = mine - theirs, theirs - mine
    unexpected_extra = extra - Counter(accepted["extra"])
    unexpected_missing = missing - Counter(accepted["missing"])
    stale_extra = Counter(accepted["extra"]) - extra
    stale_missing = Counter(accepted["missing"]) - missing
    problems = []
    if unexpected_extra:
        problems.append("we emit but SC//Design did not: %s" % sorted(unexpected_extra.elements(), key=str))
    if unexpected_missing:
        problems.append("SC//Design has but we do not: %s" % sorted(unexpected_missing.elements(), key=str))
    if stale_extra or stale_missing:
        problems.append("accepted deviation no longer happens: extra=%s missing=%s"
                        % (sorted(stale_extra.elements(), key=str), sorted(stale_missing.elements(), key=str)))
    assert not problems, "%s\n  %s" % (filename, "\n  ".join(problems))


@archive_only
def test_archive_accepted_deviations_all_name_real_files():
    assert set(ACCEPTED_DEVIATIONS) <= set(ARCHIVE_FILES)
    for filename, entry in ACCEPTED_DEVIATIONS.items():
        assert entry["reason"], filename
        assert entry["extra"] or entry["missing"], filename
